Use docker-image-builder
Replaced local builder tooling with docker image builder. The
control script now looks for updates and restarts the service
if necesary. Still work in progress though...

diff --git a/node-provisioning-service b/node-provisioning-service
--- a/node-provisioning-service
+++ b/node-provisioning-service
@@ -1,60 +1,159 @@
 #!/bin/bash
-
 # Starts a node-provisioning-service with docker
+#
+# (C) 2014 INAETICS, <www.inaetics.org> - Apache License v2.
 
-ORGDIR=`pwd`
-cd $(dirname $0)
+#
+# Config
+#
+VERBOSE_LOG=false
+BUILDER_DIR="/var/lib/docker-image-builder"
+BUILDER_REPO="https://github.com/INAETICS/docker-image-builder.git"
+BUILDER_SCRIPT="docker-image-builder"
+SERVICE_NAME="node-provisioning-service"
+SERVICE_IMAGE="inaetics/node-provisioning:latest"
+SERVICE_REPO="https://github.com/INAETICS/node-provisioning-service.git"
+RETRY_INTERVAL=30
+UPDATE_INTERVAL=31
 
-source tools/build.sh
-source tools/etcdctl.sh
-source tools/docker.sh
+#
+# Global state
+#
+current_imageid=""
+located_imageid=""
+containerid=""
 
-SVC_IMAGENAME="inaetics/node-provisioning:latest"
-SVC_IMAGEREPO="https://github.com/INAETICS/node-provisioning-service"
+#
+# Functions
+#
+
+verbose () {
+  if $VERBOSE_LOG; then $@; else $@ &> /dev/null; fi
+  return $?
+}
+
+verbose_err () {
+  if $VERBOSE_LOG; then $@; else $@ 1> /dev/null; fi
+  return $?
+}
+
+verbose_out () {
+  if $VERBOSE_LOG; then $@; else $@ 2> /dev/null; fi
+  return $?
+}
+
+update_builder () {
+  if [ ! -d "$BUILDER_DIR" ]; then 
+    echo "Cloning image builder"
+    git clone $BUILDER_REPO $BUILDER_DIR
+  else 
+    echo "Updating image builder"
+    cd $BUILDER_DIR
+    git pull
+  fi
+  if [ $? -ne 0 ]; then
+    echo "Builder update failed!" 1>&2
+    return 1
+  fi
+  return 0
+}
+
+locate_image () {
+  echo "Locating service image"
+  located_imageid=$(verbose_out $BUILDER_DIR/$BUILDER_SCRIPT locate $SERVICE_IMAGE $SERVICE_REPO)
+  if [ $? -ne 0 ]; then
+    echo "Image locate failed!" 1>&2
+    return 1
+  fi
+  echo "Located image ${located_image:0:12}"
+  return 0
+}
+
+start_service () {
+  echo "Starting service container"
+  current_imageid=$located_imageid
+  containerid=$(docker run -d -p 8080:8080 $current_imageid /tmp/node-provisioning.sh)
+  if [ $? -ne 0 ]; then
+    echo "Container start failed!" 1>&2
+    if [ "$containerid" != "" ]; then
+      docker rm -f $containerid
+      containerid=""
+    fi
+    return 1
+  fi
+  echo "Started container ${containerid:0:12}"
+  return 0 
+}
+
+stop_service () {
+  echo "Stopping service container"
+  if [ "$containerid" != "" ]; then
+    docker rm -f $containerid
+    echo "Stopped container ${containerid:0:12}"
+    containerid=""
+  fi
+  return 0
+}
 
 clean_up () {
-    docker stop node-provisioning-service > /dev/null 2>/dev/null
-    docker rm node-provisioning-service >/dev/null 2>/dev/null
-    cd $ORGDIR
+    echo "Running cleanup.."
+    stop_service
     exit 0
 }
+
+#
+# Main
+#
 trap clean_up SIGHUP SIGINT SIGTERM
 
-echo "Looking for image: ${SVC_IMAGENAME}"
-svcimage=$(docker/find_image $SVC_IMAGENAME)
-if [ ! "$svcimage" == "" ]; then
-  echo "Using local image $svcimage"
-else
-  echo "No local image found!.."
-  echo "Trying registries.."
-  registries=($(etcd/values /inaetics/docker-registry-service))
-  svcimage=$(docker/pull_image $SVC_IMAGENAME "${registries[@]}")
-
-  if [ ! "$svcimage" == "" ]; then
-    echo "Using pulled image $svcimage"
-  else
-    echo "No upstream image found!.."
-    echo "Attempting local build.."
-    tmpdir=$(mktemp -d)
-    git clone $SVC_IMAGEREPO $tmpdir
-    builder/build_image $SVC_IMAGENAME $tmpdir
-    svcimage=$(docker/find_image $SVC_IMAGENAME)
-
-    if [ "$svcimage" == "" ]; then
-      echo "Unable to locate or build image.... aborting!!" 1>&2
-      exit 1
-    fi
+for var in "$@"; do
+  if [ "$var" == "-v" ]; then
+echo "log is true"
+    VERBOSE_LOG=true
   fi
-fi
-
-echo "provisioning start"
-    docker rm node-provisioning-service >/dev/null 2>/dev/null
-docker run --name node-provisioning-service -d -p 8080:8080 $svcimage \
-    /tmp/node-provisioning.sh
-
-while true; do
-  echo "looping"
-  sleep 10 &
-  wait $!
 done
 
+echo "-----------------------------------------------------------------------"
+echo "Starting service controller"
+echo "-----------------------------------------------------------------------"
+echo -e "VERBOSE LOG\t: $VERBOSE_LOG (use -v option to enable)"
+echo -e "BUILDER_DIR\t: $BUILDER_DIR"
+echo -e "BUILDER_REPO\t: $BUILDER_REPO"
+echo -e "BUILDER_SCRIPT\t: $BUILDER_SCRIPT"
+echo -e "SERVICE_NAME\t: $SERVICE_NAME"
+echo -e "SERVICE_IMAGE\t: $SERVICE_IMAGE"
+echo -e "SERVICE_REPO\t: $SERVICE_REPO"
+echo -e "UPDATE_INTERVAL\t: $UPDATE_INTERVAL"
+echo -e "RETRY_INTERVAL\t: $RETRY_INTERVAL"
+echo "-----------------------------------------------------------------------"
+
+while true; do
+
+  verbose_err update_builder
+  if [ $? -eq 0 ]; then
+    verbose_err locate_image
+    if [ $? -eq 0 ] && [ "$current_imageid" != "$located_imageid" ]; then
+      if [ "$containerid" != "" ]; then
+        echo "Restarting with image ${located_imageid:0:12}"
+        verbose_err stop_service
+        verbose_err start_service
+      else
+        echo "Starting with image ${located_imageid:0:12}"
+        verbose_err start_service
+      fi
+    fi
+  fi
+
+  if [ "$containerid" == "" ]; then
+    echo "Not running due to previous errors"
+    echo "Will Retry in $RETRY_INTERVAL seconds..."
+    sleep $RETRY_INTERVAL &
+    wait $!
+  else
+    echo "Running in container ${containerid:0:12}"
+    echo "Will check for updates in $UPDATE_INTERVAL seconds..."
+    sleep $UPDATE_INTERVAL &
+    wait $!
+  fi
+
+done
